time:
  status: 1
Mysql:
  DataSource: root:123456@tcp(localhost:3306)/ciel?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
  MaxIdleConnes: 10
  MaxOpenConns: 50
  MaxLiftTime: 1  # unit hour
  Debug: true
CacheRedis:
  Host: localhost:6379
  Pass:
  Type: node